### ISSUE TITLE
modify sustem to system?

### ISSUE THREAD

**Issue by lopestom** [TeamWin/android_system_sepolicy#1]
https://github.com/TeamWin/android_system_sepolicy/blob/b6c4a88500ae83aac698b76a91d5a66c1bba4d49/vendor/file_contexts#L23

**Comment by bigbiff** [comment]
Not sure what this is.

**Comment by lopestom** [comment]
> /(vendor|sustem/vendor)

In the line ' /(vendor|sustem/vendor)' has sustem
Need change sustem to system as  /(vendor|**system**/vendor)
